### ISSUE TITLE
Fails when generating images one character long

### ISSUE THREAD

**Issue by thisjunewest** [citrus/magick_title#1]
In: magick_title/lib/magick_title image.rb line 85

Should be:
0 < @text.strip.length

**Comment by citrus** [comment]
Thanks for pointing this out! I've fixed the issue and released version 0.1.6. I'd be interested to know how you're using this gem and if it's working like you'd expect.

Cheers!
  -Spencer

**Comment by thisjunewest** [comment]
I'm using it on the home page of a site, for a font which is unreliable with @font-face, but it has to look good, your gem worked beautifully!

The only (other) issue I've had is that when making two images, positioned below one another, the line height between them varies with the characters used (e.g. a "g" on the top image makes a big gap between the images).

It would be good if you could give all the images the same height and font baseline, so when inline they would line up, and when stacked vertically they would have a consistent line height.

I had to do this with a PHP project last year, what I did was to render an image with all ascii characters, then use the height and baseline of that image to generate the rest of the images. I don't know if that helps here.

**Comment by citrus** [comment]
The varying heights of images has been an issue for me too. My first thought was adding a 'height' option so you can manually specify the image height. I just implemented this feature and will be releasing it shortly. I like your solution of generating a "max-height" title and basing the other titles off that figure. When I have some more time I'll look into adding this...

**Comment by citrus** [comment]
Version 0.1.7 released! You can now set the height option to make sure titles are consistent. It's a bit of a hack for now but it'll work :)

**Comment by thisjunewest** [comment]
Thanks, very helpful for my current project!
