### ISSUE TITLE
images make it by this gem always show @- as text

### ISSUE THREAD

**Issue by SeriusDavid** [citrus/magick_title#10]
i dont know why but this gem always  show @- when i try to use it

`image = MagickTitle.say(@question.content_mobile,:font => "WhitneyHTF-Book.otf",:font_path => Proc.new{ File.join MagickTitle.root, "public/fonts" },:color => '#333',:cache => false)
`

this is how im using it i really dont know why its this happening

**Comment by andrhamm** [comment]
I'm also seeing this error

**Comment by eherot** [comment]
Possibly introduced in [this commit](https://github.com/citrus/magick_title/commit/308eea8f94339d6cfe217c9ddd2ce8d6e088d071#diff-366d27c73d8724034085515acadaffe6R159)

**Comment by andrhamm** [comment]
Turns out there was a regression in ImageMagick somewhere around version 6.9.2. [Here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=28501) is a relevant thread on the IM forums. Updating to 6.9.6 should fix the problem.

UPDATE: actually, we experienced this issue on version 6.7.7.10
