### ISSUE TITLE
Line height?

### ISSUE THREAD

**Issue by thisjunewest** [citrus/magick_title#2]
Is there any chance you could add a line_height option?

**Comment by citrus** [comment]
If it's an option in imagemagick then it should be a big deal...

-Spencer

via iPhone3GS

**Comment by citrus** [comment]
So it looks like there is an option called "-interline-spacing" which should do the trick. I'll try and implement it today..

-Spencer

via iPhone3GS

**Comment by citrus** [comment]
Interline-spacing is now included as the :line_height option. Look for a new release on rubygems soon!

(fixed in ab3b51f78a135c9a6f11660297e30100027af9d1)
