### ISSUE TITLE
Quotation marks bug

### ISSUE THREAD

**Issue by thisjunewest** [citrus/magick_title#3]
It fails if you try to use single quotes!

I think the problem is on line 156 of /lib/magick_title/image.rb: `caption:'#{@text}'`.
I've tried various combinations:
- `caption:"#{@text}"`
- `caption:'#{@text.gsub("'", "\'")}'`
- `caption:"#{@text.gsub('"', '\"')}"`

However they all either fail on either single or double quotes.

I'm pretty sure this page explains how to fix it, but I haven't been able to figure it out yet:
http://www.imagemagick.org/Usage/draw/#quote

**Comment by citrus** [comment]
Thanks for pointing this out. Hopefully I'll have some time this weekend to work on a fix...

Cheers!

**Comment by citrus** [comment]
I just fixed this thanks to your link! Check out commit 308eea8f94339d6cfe217c9ddd2ce8d6e088d071 for details...
