### ISSUE TITLE
Unrecogniszed option '-interline-spacing'

### ISSUE THREAD

**Issue by thisjunewest** [citrus/magick_title#4]
Thanks for the new feature, the new styles also look really useful!

Just tried to use the new line_height and got this error, perhaps you need a specific version of image magick?

**Comment by citrus** [comment]
You're welcome! 

Did you mean to paste an error? ;)

**Comment by citrus** [comment]
Here's my IM version:

> Version: ImageMagick 6.6.4-5 2010-10-22 Q16 http://www.imagemagick.org

**Comment by citrus** [comment]
What version are you on?

**Comment by thisjunewest** [comment]
We were on ImageMagick 6.5.1, have just upgraded to the latest. Works perfectly now! thanks.

**Comment by citrus** [comment]
You're welcome!
