### ISSUE TITLE
Recursive symbolize_keys breaks other gems

### ISSUE THREAD

**Issue by pupeno** [citrus/magick_title#5]
Hello,

I just encountered an issue where the recursive symbolize_keys breaks the functionality of other gems. I think overriding this method that is used in many places in Rails with a different behaviour is destructive. If it's really necesary for the functionality of MagickTitle I would name recursive_symbolize_keys or something like that.

I originally reported the issue to factory_girl here: https://github.com/thoughtbot/factory_girl/issues/351

**Comment by citrus** [comment]
Merged #6, thank you!! I also fixed the broken tests in a9f5286. 

Let me know if you have any other issues!

-Spencer
