### ISSUE TITLE
problems with special characters

### ISSUE THREAD

**Issue by syxanash** [citrus/magick_title#7]
when I have a code like the following one:

``` ruby
require 'sinatra'
require 'magick_title'

get '/' do
  MagickTitle.say(
    'hello$world',
    :font_size => 50,
  ).to_html(false)
end
```

the method "say" doesn't return the string "hello$world", but only the word "hello".
Actually it's strange because when I write "$" inside the method say, it actually returns the character dollar, but when it's followed by a word the word it's not printed...

when I have instead the following code:

``` ruby
get '/' do
  MagickTitle.say(
    'hello$ world',
    :font_size => 50,
  ).to_html(false)
end
```

 it actually prints the string correctly and here's the result:

![hello_world_2beef1333fcc6365722b2ceba7e62dd37b1aa744](https://f.cloud.github.com/assets/1325491/1144982/90b6e7d4-1de5-11e3-8bfe-6818a773aec5.png)

**Comment by citrus** [comment]
Hmm very interesting! I'll take a look at this and see if I can figure something out. Have you tried escaping the dollar sign? `hello\$world`

**Comment by syxanash** [comment]
oh actually I didn't really pay attention to this detail :P
I just replaced the double quotes in my previous code with single quotes and escaped the dollar, it works perfectly now...

``` ruby
get '/' do
  MagickTitle.say(
    'hello\$world',
    :font_size => 50,
  ).to_html(false)
end
```

![helloworld_5efb85d117eec1927e687785c620c775f741764e](https://f.cloud.github.com/assets/1325491/1151611/bdb5fef0-1efd-11e3-89f4-712772b8dc9f.png)

thanks!

**Comment by citrus** [comment]
Right on, glad it works! :beers:
