### ISSUE TITLE
problem with non English charactores

### ISSUE THREAD

**Issue by eshaiju** [citrus/magick_title#8]
when I have a code like the following one 
MagickTitle.say("മലയാളം")
i got image like this
![_65908a24241889d7f01eecc2c0aee8707df6cd61](https://cloud.githubusercontent.com/assets/2918256/3202576/1605142a-ed92-11e3-96b7-999f25ed7c0b.png)

**Comment by citrus** [comment]
Could it be that the font you're using doesn't have those characters?

**Comment by eshaiju** [comment]
hi this is fixed by adding a malayalam font , thanks

**Comment by citrus** [comment]
No worries-- cheers!
