### ISSUE TITLE
File name change

### ISSUE THREAD

**Issue by qaswm** [citrus/magick_title#9]
I want to use something different to create the filename. The current setup uses the text which is provided to generate the filename and with my requirements that is not desired.

Any ideas.

**Comment by citrus** [comment]
@qaswm Best would be to add `filename` as an option that gets passed into `MagickTitle::Image` then check for the option on [line 57](https://github.com/citrus/magick_title/blob/master/lib/magick_title/image.rb#L57) instead of generating the name..

**Comment by qaswm** [comment]
I am not that great with rails, will this mean I fork and modify and then commit my own gem for this?

**Comment by citrus** [comment]
yep that would be the approach @qaswm .. open a pull request and I'll merge it into my repo.
